spring.application.name=mano


spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Actuators
management.endpoints.web.exposure.include=*

#logging.level.root=OFF
#logging.level.com.example.loggingaspect=DEBUG

#log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n

server.port=8092