spring.application.name=mano


spring.datasource.url=jdbc:postgresql://localhost:5432/Asset
spring.datasource.username=postgres
spring.datasource.password=manoj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect